baseURL = "https://blog.sayrainsky.com/"
languageCode = "zh-cn"
title = "Sayrain's Blog"
theme = "yinyang"
DefaultContentLanguage = "cn"

[author]
  name = "sayrainsky"
  homepage = "https://blog.sayrainsky.com/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 2

[params]
mainSections = ["posts"]
headTitle = "sayrainsky"
[[params.socials]]
name = "关于我"
link = "https://blog.sayrainsky.com/"
[[params.socials]]
name = "Github"
link = "https://github.com/sayrain"
postHeaderContent = ""
postFooterContent = ""
extraCSSFiles = []